SELECT B.TITLE, B.BOARD_ID, Y.REPLY_ID, Y.WRITER_ID, Y.CONTENTS, TO_CHAR(Y.CREATED_DATE, 'yyyy-mm-dd') CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY Y
WHERE B.BOARD_ID = Y.BOARD_ID
AND TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY Y.CREATED_DATE, B.TITLE